# CRIE UM PROGRAMA QUE O USUARIO POSSA DIGITAR VARIOS VALORES NUMERICOS E CADASTRE-OS EM UMA
# LISTA, CASO O NUMERO JA ESTEJA NA LISTA, ELE NÃO SERÁ ADICIONADO. NO FINAL, SERÃO EXIBIDOS
# TODOS OS VALORES UNICOS DIGITADOS EM ORDEM CRESCENTE.

